name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue.

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A brief description of the bug
      placeholder: "Enter a brief title for the bug"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the bug
      placeholder: "Describe the bug in detail"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      placeholder: "List the steps to reproduce the bug"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: "Describe the expected behavior"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened
      placeholder: "Describe the actual behavior"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
      placeholder: "Add any screenshots here"

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Provide details about your environment:
        - OS: [e.g. Windows, Mac, Linux]
        - Browser: [e.g. Chrome, Safari, Firefox]
        - Version: [e.g. 22]
      placeholder: "Enter details about your environment"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Add any other context or information"