name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your idea.

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: A brief title for the feature request
      placeholder: "Enter a brief title for the feature"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the feature request
      placeholder: "Describe the feature in detail"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Explain why this feature should be added:
        - What problem does it solve?
        - How will it improve the project?
      placeholder: "Explain the motivation behind this feature"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Describe any alternative solutions or features you've considered.
      placeholder: "Describe any alternative solutions or features"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: "Add any other context or information"
    validations:
      required: false